version: v0.0.0
time_zone: JST
logging:
  logger: glg
  level: debug
  format: raw
server_config:
  servers:
    - name: agent-grpc
      host: 0.0.0.0
      port: 8081
      mode: GRPC
      probe_wait_time: "3s"
      http:
        shutdown_duration: "5s"
        handler_timeout: ""
        idle_timeout: ""
        read_header_timeout: ""
        read_timeout: ""
        write_timeout: ""
  startup_strategy:
    - agent-grpc
  shutdown_strategy:
    - agent-grpc
  full_shutdown_duration: 600s
  tls:
    enabled: false
    # cert: /path/to/cert
    # key: /path/to/key
    # ca: /path/to/ca
ngt:
  # path to index data
  index_path: "/etc/server/backup"
  # vector dimension
  dimension: 768
  # bulk insert chunk size
  bulk_insert_chunk_size: 10
  # distance_type, which should be "l1", "l2" "angle", "hamming", "cosine", "normalizedangle", "normalizedcosine" or "jaccard"
  distance_type: cosine
  # object_type, which should be "float" or "uint8"
  object_type: float
  # creation edge size
  creation_edge_size: 20
  # search edge size
  search_edge_size: 10
  # The limit duration of automatic indexing
  # auto_index_duration_limit should be 30m-6h for production use. Below setting is a just example
  #auto_index_duration_limit: 1m
  auto_index_duration_limit: 10s
  # Check duration of automatic indexing.
  # auto_index_check_duration be 10m-1h for production use. Below setting is a just example
  auto_index_check_duration: 5m
  # The number of cache to trigger automatic indexing
  auto_index_length: 100
  # The limit duration of auto saving indexing
  # auto_save_index_duration should be 30m-60m for production use. The below setting is a just example.
  #auto_save_index_duration: 90s
  auto_save_index_duration: 10s
  # The maximum limit duration for an initial delay
  # initial_delay_max_duration should be 3m-5m for production use. The below setting is a just example.
  #initial_delay_max_duration: 60s
  initial_delay_max_duration: 10s
  # The default create index batch pool size.
  # When it is too large comparing to machine resource, the docker container will be crash.
  default_pool_size: 500
